Android SafetyNet
tweag/webauthn pull request #79
Opened 2022-01-06 13:10 UTC by ErinvanderVeen

Draft PR, still needs documentation and a rewrite of the commits.

2022-01-06 13:38 UTC, ErinvanderVeen commented
We should also decide if we want to test `ctsProfileMatch`, `basicIntegrity` or neither.

2022-01-06 15:03 UTC, Infinisil requested changes

2022-01-06 15:03 UTC, Infinisil commented on src/Crypto/WebAuthn/Operations/Attestation/AndroidSafetyNet.hs
> +    unless (nonceBS == encodedData) . Left $ VerificationErrorInvalidSignature
This uses `BSC.pack` which seems to be a bit weird, as it interprets text, which might have an encoding, as just bytes, and then compares that to other bytes. With `nonce` being a `Text`, I think it's better to go the other way: Encode the `encodedData` as UTF-8 to get a `Text`, then compare that.

```suggestion
    let encodedData = encodeUtf8 . Base64.encode $ BA.convert hashedData
    unless (nonce response == encodedData) . Left $ VerificationErrorInvalidSignature
```

2022-01-06 15:10 UTC, ErinvanderVeen commented on src/Crypto/WebAuthn/Operations/Attestation/AndroidSafetyNet.hs
> +    NE.toList <$> mapM JOSE.fromX509Certificate chain
I did that before, but was confused why the function expects the result to be a list.

2022-01-06 15:16 UTC, Infinisil commented on src/Crypto/WebAuthn/Operations/Attestation/AndroidSafetyNet.hs
> +    basicIntegrity :: Bool,
Regarding these values, I think they should be checked to be both true. We can later also make it configurable, which could look like this:
```haskell
data RequiredIntegrity
  = NoIntegrity
  | BasicIntegrity
  | PassedCTS
```

With links to the docs in https://developer.android.com/training/safetynet/attestation.html#compat-check-response

2022-01-07 10:17 UTC, ErinvanderVeen commented on src/Crypto/WebAuthn/Operations/Attestation/AndroidSafetyNet.hs
> +        jws :: JOSE.CompactJWS JOSE.JWSHeader <- first DecodingErrorJOSEError $ runExcept $ JOSE.decodeCompact (LB.fromStrict responseRaw)
I think this is more clear, because we use `verifyJWS` and the standard only mentions jws.

2022-01-07 11:29 UTC, Infinisil commented on src/Crypto/WebAuthn/Operations/Attestation/AndroidSafetyNet.hs
> +      }
```suggestion
format :: M.SomeAttestationStatementFormat
format past future =
  M.SomeAttestationStatementFormat $
    Format
      { driftBackwardsTolerance = mempty {HG.durationSeconds = 60},
        driftForwardsTolerance = mempty
      }
```

2022-01-10 12:57 UTC, Infinisil approved these changes

2022-01-10 14:08 UTC, merged