Pubkey cleanup
tweag/webauthn pull request #80
Opened 2022-01-06 21:15 UTC by Infinisil

2022-01-12 05:59 UTC, Infinisil commented
Still to do is cleaning up the tests

2022-01-12 08:05 UTC, ErinvanderVeen commented on src/Crypto/WebAuthn/PublicKey.hs
> +        -- octets MUST be preserved.
Probably best to reference TPM to explain why we need the leading zeroes.

2022-01-12 10:53 UTC, ErinvanderVeen requested changes

2022-01-12 10:53 UTC, ErinvanderVeen commented on src/Crypto/WebAuthn/Cose/Key.hs
> +    -- is used.
Your vim wraps lines with two spaces.
```
set nojoinspaces
```

2022-01-13 11:09 UTC, ErinvanderVeen approved these changes

2022-01-13 11:09 UTC, merged